### ISSUE TITLE
Add the version of ovh-ui-kit to the url in @font-face

### ISSUE THREAD

**Issue by Jisay** [ovh-ux/ovh-ui-kit#140]
To avoid server side cache of the differents icons fonts format the version of the ovh-ui-kit should be added to the end of the url setted here : 
https://github.com/ovh-ux/ovh-ui-kit/blob/144e793cf351efb10e68fed25aa9e594dc277889/packages/oui-icons/fonts.less#L5-L9

Like this cache will be invalidated at each new version of the component.

**Comment by AxelPeter** [comment]
Done with the release v2.2.0
I close the issue.
