### ISSUE TITLE
oui-angular/numeric 'default' displays 4 and a half digits

### ISSUE THREAD

**Issue by angeldev1** [ovh-ux/ovh-ui-kit#186]
oui-angular/numeric 'default' displays 4 and a half digits when aria-valuenow="99999".

**Comment by AxelPeter** [comment]
Thanks for your feedback !
We'll check about this :)

**Comment by AxelPeter** [comment]
Will be resolved with v2.17.0 (https://github.com/ovh-ux/ovh-ui-kit/commit/f874a07fa5f3d28b4f0cf6cc3727bc9b4ae386d7)
