### ISSUE TITLE
RFS for font-size?

### ISSUE THREAD

**Issue by feoche** [ovh-ux/ovh-ui-kit#382]
### Description

I just saw this package (https://github.com/twbs/rfs) for responsive font-size, should it be integrated inside ui-kit?
Example :
```
.oui-icon {
   // font-size: rem-calc(4rem); // old way
   .font-size(4rem);
}
```
generates as
```
.oui-icon {
  font-size: 4rem;
}

@media (max-width: 1200px) {
  .oui-icon {
    font-size: calc(1.525rem + 3.3vw);
  }
}
```

**Comment by AxelPeter** [comment]
With our use of icons, I think it's more appropriate to adapt the size to the parent `font-size`.
In this case, we don't need to override the default size when they're added in a component (eg. https://github.com/ovh-ux/ovh-ui-kit/blob/master/packages/oui-button/_mixins.less#L202).

We could still have helpers that set sizes, like we have with our fields or our loaders.
