### ISSUE TITLE
add compiled dist

### ISSUE THREAD

**Issue by makidelille** [ovh-ux/ovh-ui-kit#47]
hello,

can we have a precompiled css, instead of having to compile less in our apps ?

thanks

**Comment by mlarose** [comment]
i propose making a cds plan that will test/lint the code and automatically generate the dist/css on the master branch

**Comment by neolitec** [comment]
NPM script "prepublish" can be used to execute the CSS compilation just before publishing the package on NPM.
IMHO, dist should never be commited. In addition, if the package is installed directly from GitHub URL, maybe a script "postinstall" can also compile the CSS...
